Make bulk search fast
nexB/vulnerablecode pull request #1017
Opened 2022-11-25 15:24 UTC by TG1999

Signed-off-by: Tushar Goel <tushar.goel.dav@gmail.com>

2022-11-25 15:49 UTC, pombredanne requested changes
Thanks!
See feedback inline.

2022-11-25 15:49 UTC, pombredanne commented on vulnerabilities/migrations/0034_package_package.py
> +            model_name='package',
This means you are storing the concrete purl, and this makes 100% sense. But then call it purl or pakage_url and replace/override anything we have already.

2022-11-25 15:49 UTC, pombredanne commented on vulnerabilities/migrations/0034_package_package.py
> +            field=models.CharField(blank=True, help_text='The Package URL for this package.', max_length=255),
This should not be blank ever once migrated, so you would need a third migration once the data is updated.

2022-11-25 15:49 UTC, pombredanne commented on vulnerabilities/models.py
> +        max_length=255,
It would have to be indexed

2022-11-25 15:49 UTC, pombredanne commented on vulnerabilities/models.py
> +        self.package = self.purl
as explained above this would replace entirely the self.purl.

2022-11-25 15:49 UTC, pombredanne commented on vulnerabilities/migrations/0035_auto_20221125_1257.py
> +# Generated by Django 4.0.7 on 2022-11-25 12:57
You need a better migration script name as this is not a generated migration, is it?

2022-11-25 15:49 UTC, pombredanne commented on vulnerabilities/migrations/0035_auto_20221125_1257.py
> +        for package in Package.objects.all():
you need to create a bulk migration, not one at a time

2022-11-25 18:03 UTC, TG1999 commented
@pombredanne the tests where we ignore qualifiers and subpath are failing because we are matching purls directly without removing qualifiers and subpath, what I suggest as a solution is to store `purl_without_qualifiers_subpath` as a different field and remove qualifiers and subpath from incoming purls and match the list like we are doing now.

2022-11-28 07:14 UTC, tdruez commented on vulnerabilities/api.py
> +            query.filter(packagerelatedvulnerability__fix=False).only("package").distinct()
I'm wondering why you do not use the same syntax as in the `all` action?
ie: `.vulnerable().only("package_url")`
Are you fetching something different here?

2022-11-28 12:13 UTC, tdruez commented
> @pombredanne the tests where we ignore qualifiers and subpath are failing because we are matching purls directly without removing qualifiers and subpath, what I suggest as a solution is to store purl_without_qualifiers_subpath as a different field and remove qualifiers and subpath from incoming purls and match the list like we are doing now.

Yes, you should store both full purl and plain purl and allow to run the matching on the plain purl.

2022-11-28 15:27 UTC, tdruez approved these changes

2022-11-28 21:14 UTC, pombredanne commented on vulnerabilities/models.py
> +    plain_package_url = models.CharField(
I am not in love with the `plain_package_url` name but this makes sense for now. We will need to find a better way.
I will merge for now!

2022-11-28 21:16 UTC, pombredanne approved these changes
Thanks! This will need to be refined name wise but this is a good fix for now.
Merging

2022-11-28 21:16 UTC, merged