Migrate mozilla importer
nexB/vulnerablecode pull request #1043
Opened 2022-12-13 21:27 UTC by TG1999

Signed-off-by: Tushar Goel <tushar.goel.dav@gmail.com>

2022-12-24 16:19 UTC, pombredanne requested changes
Thanks! See some nits for your review.

2022-12-24 16:19 UTC, pombredanne commented on vulnerabilities/tests/test_mozilla.py
> +def test_import():
These should be two different tests IMHO, not one.
Also you would nee to delete https://github.com/nexB/vulnerablecode/blob/main/vulnerabilities/tests/test_data/mozilla.zip but you may want to make sure we cover all the test cases that were in that zip

2022-12-26 10:25 UTC, TG1999 commented on vulnerabilities/tests/test_mozilla.py
> +def test_import():
@pombredanne will separate the tests and delete `mozilla.zip`, in these new tests we are asserting the whole advisory at once and not checking every property one by one.

2023-01-06 15:17 UTC, pombredanne approved these changes
LGTM!

2023-01-06 15:17 UTC, TG1999 reviewed
some suggestions

2023-01-06 15:17 UTC, TG1999 commented on vulnerabilities/importers/mozilla.py
> +        version = pkg.rsplit(None, 1)[1]
```suggestion
        name, _, version = pkg.rpartition(" ")
```

2023-01-06 15:17 UTC, TG1999 commented on vulnerabilities/importers/mozilla.py
> +        alias = is_cve(cve)
```suggestion
```

2023-01-06 15:17 UTC, TG1999 commented on vulnerabilities/importers/mozilla.py
> +        name = pkg.rsplit(None, 1)[0]
```suggestion
```

2023-01-09 13:12 UTC, merged