Add support for conan advisories
nexB/vulnerablecode pull request #1155
Opened 2023-03-21 10:59 UTC by TG1999

2023-03-28 12:38 UTC, pombredanne requested changes
Thanks... See a nit inlined and you need to add a CHANGELOG entry too!

2023-03-28 12:38 UTC, pombredanne commented on vulnerabilities/package_managers.py
> +    Fetch versions of Erlang packages from the hex API
Erlang and hex?

2023-03-28 12:48 UTC, TG1999 commented on vulnerabilities/package_managers.py
> +    Fetch versions of Erlang packages from the hex API
Done!

2023-03-29 08:26 UTC, pombredanne approved these changes
LGTM! Thanks.

2023-03-29 08:27 UTC, merged