Write packages and vulnerabilities at the time of import
nexB/vulnerablecode pull request #1280
Opened 2023-08-28 14:41 UTC by TG1999

2023-08-30 16:58 UTC, pombredanne requested changes
Some nits for your consideration.

2023-08-30 16:58 UTC, pombredanne commented on vulnerabilities/improve_runner.py
> +    def __init__(self, improver_class=None, improver: Improver = None):
May be keeping the class design and passing kwargs can work too?
```suggestion
    def __init__(self, improver_class, **kwargs):
    self.improver = improver_class(**kwargs)
```

2023-08-30 16:58 UTC, pombredanne commented on vulnerabilities/improve_runner.py
> +        summary = summary.strip()
This may be best in another PR

2023-08-31 17:19 UTC, TG1999 commented
@DennisClark we need your input on this, we use advisories as a screenshot of the status of the advisory at a given point of time. A single advisory goes through many improver processes to draw inferences, what should be the best possible way to get a status on advisory model to know which improvers have already ran through a particular advisory ?

2023-08-31 18:45 UTC, DennisClark commented
@TG1999   Here are a few thoughts about advisories: 
* every advisory should be associated with a "date_detected" (or similar), which can be the date+time that the advisory was originally posted to VC. 
* since the number and types of potential improvers can vary, we may want to create a field (perhaps "associated_improvers") that can contain one or more pairs of improver_name:improver_date values, perhaps in a json structure or similar, that is updated whenever an improver is processed on the advisory 
* alternatively, the new field would initially identify all the potential improver_name values with a null in the improver_date that is set when the improver is actually run for that advisory
* all of those new elements should be visible in the VCIO UI. 
* the process(es) to initiate advisory improvements should select those where an appropriate improver has not yet been processed for that advisory. 

I don't think we necessarily need a "status" on the advisory, since the list of improver_name:improver_date values ought to give us what would be really useful here (what has been run and when).

2023-09-12 16:31 UTC, pombredanne requested changes
Here are some nits for your consideration

2023-09-14 14:18 UTC, TG1999 commented on vulnerabilities/import_runner.py
> +                    continue
We are logging it already here https://github.com/nexB/vulnerablecode/pull/1280/files#diff-11856d929972b1aa71dcd476298a831d6b598b291c0638057af6d62050ba4a15R225

2023-09-14 14:18 UTC, TG1999 commented on vulnerabilities/import_runner.py
> +            self.do_import(advisories)
Opened follow-up issue here https://github.com/nexB/vulnerablecode/issues/1300

2023-09-14 14:19 UTC, TG1999 commented on vulnerabilities/import_runner.py
> +        improver = AdvisoryBasedDefaultImprover(advisories=advisories)
Done!

2023-09-14 14:23 UTC, TG1999 commented on vulnerabilities/migrations/0040_remove_advisory_date_improved_advisory_date_imported.py
> +            name="date_improved",
We have replaced `date_improved` with `date_imported` here, `date_improved` used to be updated every time when any improver runs on the advisory, which was not helping

2023-09-21 16:25 UTC, pombredanne reviewed
Here are a few nits... Either apply now or later!
LGTM otherwise!

2023-09-21 16:25 UTC, pombredanne commented on vulnerabilities/import_runner.py
> +        logger.info("Finished improving using %s.", advisory_importer.__class__.qualified_name)
```suggestion
        logger.info("Finished importing using %s.", advisory_importer.__class__.qualified_name)
```

2023-09-21 17:57 UTC, merged