add-curl-advisories-importer
nexB/vulnerablecode pull request #1402
Opened 2024-01-25 11:34 UTC by ambuj-1211

The test file is a dummy and will be completed once the curl.py importer is completed.

2024-01-25 14:36 UTC, TG1999 requested changes
@ambuj-1211 thanks ++ for your contribution, I have added some comments for your consideration. Also run `make valid` command for fixing formatting errors.

2024-01-25 14:36 UTC, TG1999 commented on vulntotal/tests/test_osv.py
> +        assert results == expected
This change is not required

2024-01-25 14:36 UTC, TG1999 commented on vulnerabilities/importers/curl.py
> +import logging
Add header

2024-01-25 14:36 UTC, TG1999 commented on vulnerabilities/importers/curl.py
> +    def get_response(self):
Please check utils.py and import `fetch_response` the function from there

2024-01-25 14:36 UTC, TG1999 commented on vulnerabilities/importers/curl.py
> +            cve_id = data["aliases"]
What if "aliases" is not in data ? And will aliases be a string or a list ?
```suggestion
            cve_id = data.get("aliases") or ""
```

2024-01-25 14:36 UTC, TG1999 commented on vulnerabilities/importers/curl.py
> +                logger.error(f"Invalid CVE ID: {cve_id} in package {data['database_specific']['package']}")
Use get method to extract data from dictionary

2024-01-25 14:36 UTC, TG1999 commented on vulnerabilities/importers/curl.py
> +    fixed_version = SemverVersion(raw_data["affected"][0]["ranges"][0]["events"][1]["fixed"])
```suggestion
    fixed_version = SemverVersion(raw_data["affected"][0]["ranges"][0]["events"][1]["fixed"])
```
Check `get_item` method in utils.py and before accessing any index check the length of list

2024-01-25 14:42 UTC, TG1999 commented
@ambuj-1211 additionally please sign-off your commits

2024-01-31 17:37 UTC, ambuj-1211 commented
@TG1999  Apologies for the late response, I was stuck in my end sem exams. Done some changes as mentioned. I also want to know what to do for pURL, as in what should be the type, package name, and other components of the purl and also the version range for curl is not defined in univers what to do for that?

2024-02-06 11:55 UTC, TG1999 commented
type-generic namespace-domain name i.e curl.se name - name of the tool (curl, tiny-curl), version - as specified, download_url as qualifiers, so https://curl.se/download/curl-8.6.0.tar.gz this will be `pkg:generic/curl.se/curl@8.6.0?download_url=https://curl.se/download/curl-8.6.0.tar.gz`

2024-02-06 12:00 UTC, TG1999 commented
@ambuj-1211 try to collect all the versions of curl and commit a test to check with univers if all versions are effectively Semver Version

2024-03-10 12:25 UTC, ambuj-1211 commented
@TG1999 done the changes please review the commits

2024-03-17 18:43 UTC, closed without merging

2024-03-26 18:58 UTC, pombredanne commented
@ambuj-1211 hey, you are not planning to complete this after all?

2024-03-28 08:30 UTC, ambuj-1211 commented
I made a new pr regarding this issue therefore I closed this one, because there were some problems with that branch which I was not able to amend.