Add a basic model for Known Exploited Vulnerabilities
nexB/vulnerablecode pull request #1422
Opened 2024-02-18 11:22 UTC by ziadhany

![Screenshot 2024-02-18 at 13-18-29 VulnerableCode Vulnerability Details - VCID-111c-u9bh-aaac](https://github.com/nexB/vulnerablecode/assets/29133904/8468fd51-9887-4b1a-947a-74b96b108a07)

This is fake data but I think something like this is a good start

2024-02-26 18:40 UTC, TG1999 commented
I think we need a new tab for this, @DennisClark what's your initial thoughts on this ?

2024-03-12 14:57 UTC, ziadhany commented on vulnerabilities/improvers/vulnerability_kev.py
> +        return [Advisory.objects.all()[0]]
I am not sure if this is the right way to just run the improver

2024-07-12 11:43 UTC, keshav-space requested changes
@ziadhany Thanks ++ 
Looking good! see minor nits for your consideration.
Also, please add some tests.

2024-07-12 11:43 UTC, keshav-space commented on vulnerabilities/improvers/vulnerability_kev.py
> +
Add a `TODO` to revisit this once we have a better, improved design. The current `Improver` design is constraining.

2024-07-12 21:44 UTC, ziadhany commented on vulnerabilities/improvers/vulnerability_kev.py
> +        return [Advisory.objects.all()[0]]
Done

2024-07-12 21:44 UTC, ziadhany commented on vulnerabilities/improvers/vulnerability_kev.py
> +
Done

2024-07-15 10:30 UTC, keshav-space approved these changes
Thanks @ziadhany, Merging!

2024-07-15 10:34 UTC, merged