Expose Advisory details in API
nexB/vulnerablecode pull request #1459
Opened 2024-04-10 12:40 UTC by ykodwani01

Solves issue https://github.com/nexB/vulnerablecode/issues/1433

Signed-off-by: Yash Kodwani <yashkodwani2003@gmail.com>

2024-04-10 12:41 UTC, ykodwani01 commented
@pombredanne @ziadhany  Can you please review and let me know if any changes required

2024-04-10 14:04 UTC, ziadhany commented
@ykodwani01 the CI ( code style is failing  )

Don't forget to run `make valid` in the terminal to check the code style before you commit.

2024-04-11 15:48 UTC, ziadhany requested changes
@ykodwani01 Looks good! but I think the most important data we want to expose ( `date_collected`, `created_by` and `url` )

2024-04-11 15:48 UTC, ziadhany commented on vulnerabilities/api.py
> +            for i in advisory_objects:
please try to use meaningful variable names when iterating (  `i`,  `itr` )

```suggestion
            for advisory_object in advisory_objects:
```

2024-04-12 20:18 UTC, ykodwani01 commented
@ziadhany Done with the required changes

2024-04-12 22:23 UTC, ziadhany commented
> @ziadhany Done with the required changes.
> 
> There is a problem with DCO, I committed one change directly from github which caused error and now Its failing the test. Can you suggest something to resolve it.

You can read these two articles :
- https://github.com/src-d/guide/blob/master/developer-community/fix-DCO.md
- https://medium.com/@michaelyuan_88928/a-complete-guide-to-dco-for-open-source-developers-fa063c17d9e7

2024-04-13 13:08 UTC, closed without merging

2024-04-13 13:21 UTC, ykodwani01 commented
New PR is raised at https://github.com/nexB/vulnerablecode/pull/1461