[Experiment] Store and evaluate package version ranges
nexB/vulnerablecode pull request #270
Opened 2020-10-23 13:51 UTC by sbs2001

- Add a table VulnerablePackageVersionRange
- This table stores version less purl string and a FK of vulnerability
- Added manager method which on given  a purl string which does not exist in the db
  tries to find whether it satisfies a version  range, if yes then that vulnerability is returned

Signed-off-by: Shivam Sandbhor <shivam.sandbhor@gmail.com>

2020-11-17 22:47 UTC, pombredanne requested changes
Thanks! I reckon this still an experiment and a WIP, but getting some more tests here would be essential. I think we will need this for sure.
I added some other comments for your consideration.

2020-11-17 22:47 UTC, pombredanne commented on vulnerabilities/data_source.py
> +# This dataclass is nested inside the `Advisory` class below. It is used
Should this be a docstring instead of a comment?

2020-11-17 22:47 UTC, pombredanne commented on vulnerabilities/data_source.py
> +    version_ranges: str
I called this a requirement in scancode https://github.com/nexB/scancode-toolkit/blob/ba4bbf216c6f44572662d16c76214a08b0a69e7e/src/packagedcode/models.py#L331
I wonder if we should rename it in scancode or here.... but in anycase I would like to keep in a single common name for the same concept.

2020-11-17 22:47 UTC, pombredanne commented on vulnerabilities/data_source.py
> +class VulnPkgVersionRange:
Could we find a better name?
PackageSpecification may be? what else could be a good one?

2020-11-17 22:47 UTC, pombredanne commented on vulnerabilities/data_source.py
> +    vuln_pkg_version_ranges : Iterable[VulnPkgVersionRange]
I reckon you would want that `vuln_pkg_version_ranges` be optional? and replace the the `impacted_package_urls` ?
Or would we keep both?
Could you have both at the same time?
And if we have bot would these be rather names something like `impacted_package_urls_specification` , or ``impacted_package_urls_requirements` or `impacted_package_urls_version ranges` or ...?`

2020-11-17 22:47 UTC, pombredanne commented on vulnerabilities/importer_yielder.py
> +            'ecosystems': ['MAVEN', 'NUGET']
Why dropping composer from here?

2020-11-18 06:23 UTC, sbs2001 commented
@pombredanne  Thanks for the review. 

What kind of  cases should be covered by these tests ?

Re. naming  no strong opinions  here but IMHO `requirement` isn't as intuitive as `version_ranges` .

2020-11-23 16:42 UTC, pombredanne commented on vulnerabilities/importer_yielder.py
> +            'ecosystems': ['MAVEN', 'NUGET']
And actually why even filtering based on "ecosystems" ? Why not get them all?

2020-11-23 16:43 UTC, pombredanne commented
> @pombredanne Thanks for the review.
> What kind of cases should be covered by these tests ?
> Re. naming no strong opinions here but IMHO `requirement` isn't as intuitive as `version_ranges` 

I am fine with `version_ranges`. The key is  consistency, so if you go with it, we need to adopt that in scancode-toolkit and scancode.io too. Can you also enter tickets there? (and link back here too?)

2021-03-04 11:58 UTC, closed without merging