Fix and renable safetydb importer
nexB/vulnerablecode pull request #273
Opened 2020-10-30 08:10 UTC by sbs2001

Fixes https://github.com/nexB/vulnerablecode/issues/244

Signed-off-by: Shivam Sandbhor <shivam.sandbhor@gmail.com>

2020-11-17 22:50 UTC, pombredanne requested changes
This looks fine but we cannot have this enabled by default license-wise for now. How could we have a way to enable this on demand?

2020-11-17 22:50 UTC, pombredanne commented on vulnerabilities/importer_yielder.py
> +    {
We need to have a way to selectively enable some non-free resources like this one. As long as this is under a cc-by-nc  license we cannot integrate these data by default IMHO 
@jayfk ping?

2020-11-19 11:07 UTC, sbs2001 commented
@pombredanne  from the discussion we had, you suggested we handle this  by using a config file which contains a list of licenses. 
If an importer's license is not present in this list either run/don't run the importer. 

I think this logic belongs in the `importer_yielder.py` file, no need to create another config file.

2020-12-11 12:23 UTC, pombredanne commented on vulnerabilities/importer_yielder.py
> +    },
Let's add instead a flag to disable this rather than commenting it out and leave this disabled.

2021-02-24 08:48 UTC, sbs2001 commented
Commits included in https://github.com/nexB/vulnerablecode/pull/259. Hence closing

2021-02-24 08:48 UTC, closed without merging