Improve docs
nexB/vulnerablecode pull request #316
Opened 2021-01-27 13:47 UTC by pombredanne

This PR refines the README documentation.

2021-01-29 04:42 UTC, sbs2001 requested changes
Thanks ! This is better, please  correct the typos I've highlighted, and we're good to merge this.

2021-01-29 12:47 UTC, pombredanne commented
> Thanks ! This is better, please correct the typos I've highlighted, and we're good to merge this.

I could not see comments about typos, may be you did not submit your review yet and the comments are still pending the full review submissian?

2021-01-29 14:15 UTC, sbs2001 requested changes

2021-01-29 14:15 UTC, sbs2001 commented on README.rst
> +CPEs. This makes packeg queries more dpscific and more accurate to answer
This line contains 2 typos

2021-01-29 14:16 UTC, sbs2001 commented
@pombredanne  I don't know what happened, anyways I've commented the line with typos

2021-02-13 04:51 UTC, sbs2001 commented
I commited typo fixes and merging this.

2021-02-13 04:53 UTC, merged