[WIP]Send severity data along with vulnerability
nexB/vulnerablecode pull request #369
Opened 2021-03-05 14:01 UTC by sbs2001

Fix https://github.com/nexB/vulnerablecode/issues/351
Signed-off-by: Shivam Sandbhor <shivam.sandbhor@gmail.com>

2021-03-09 11:31 UTC, pombredanne requested changes
Thanks!
See the proposed changes below for your consideration.

2021-03-09 11:31 UTC, pombredanne commented on vulnerabilities/tests/test_api.py
> +                "url": "http://testserver/api/packages/3467",
We should not leak the PostgreSQL PK here. Either use a natural key or a UUID, not the pk.
This could be done in another ticket, so not absolutely needed here.

2021-03-09 11:31 UTC, pombredanne commented on vulnerabilities/tests/test_api.py
> +        # This normalization is brittle
Use something less ugly that does the clean up in a clear way., e.g. more or less..
```suggestion
def clean_response(response):
    """
    Return a cleaned response suitable for comparison in tests in particular:
    - sort lists with a stable order
    - remove transient values such as primary keys or dates that may change between calls.
    """
    for item in response:
        for unresolved_vulnerability in item["unresolved_vulnerabilities"]:
                .....         
        
    
                # This normalization is brittle
```

2021-03-09 11:31 UTC, pombredanne commented on vulnerabilities/tests/test_api.py
> +            {},
What is this? IMHO it would be better to return an actual data structure like below, with no vulnerabilities

2021-03-09 11:31 UTC, pombredanne commented on vulnerabilities/tests/test_api.py
> +        expected_response = [
Very soon, we will need to move these to file.

2021-03-09 11:31 UTC, pombredanne commented on vulnerabilities/tests/test_api.py
> +                "purl": "pkg:maven/com.datadoghq/datadog-api-client@1.0.0-beta.7",
This should be towards the top

2021-03-10 14:41 UTC, sbs2001 commented on vulnerabilities/tests/test_api.py
> +            {},
Done

2021-03-11 04:10 UTC, merged

2021-03-11 16:45 UTC, sbs2001 commented
For the POST request to `/api/packages/bulk_search` with the body as 

```
{
            "purls": [
                "pkg:deb/debian/doesnotexist@0.9.7-10?distro=jessie",
                "pkg:maven/com.datadoghq/datadog-api-client@1.0.0-beta.7",
            ]
        }
```


The response looks like : 

```
[
            {
                "name": "doesnotexist",
                "namespace": "debian",
                "qualifiers": {"distro": "jessie"},
                "resolved_vulnerabilities": [],
                "subpath": None,
                "type": "deb",
                "unresolved_vulnerabilities": [],
                "version": "0.9.7-10",
            },
            {
                "name": "datadog-api-client",
                "namespace": "com.datadoghq",
                "purl": "pkg:maven/com.datadoghq/datadog-api-client@1.0.0-beta.7",
                "qualifiers": {},
                "resolved_vulnerabilities": [],
                "subpath": "",
                "type": "maven",
                "version": "1.0.0-beta.7",
                "url": "http://testserver/api/packages/3467",
                "unresolved_vulnerabilities": [
                    {
                        "references": [
                            {
                                "reference_id": "",
                                "scores": [],
                                "source": "",
                                "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-21331",
                            },
                            {
                                "reference_id": "GHSA-2cxf-6567-7pp6",
                                "scores": [{"scoring_system": "cvssv3.1_qr", "value": "LOW"}],
                                "source": "",
                                "url": "https://github.com/DataDog/datadog-api-client-java/security/advisories/GHSA-2cxf-6567-7pp6",
                            },
                            {
                                "reference_id": "GHSA-2cxf-6567-7pp6",
                                "scores": [],
                                "source": "",
                                "url": "https://github.com/advisories/GHSA-2cxf-6567-7pp6",
                            },
                        ],
                        "url": "http://testserver/api/vulnerabilities/60",
                        "vulnerability_id": "CVE-2021-21331",
                    }
                ],

            },
        ]
```

2021-03-11 19:33 UTC, pombredanne commented
@sbs2001 can we add the comment above to the doc?

2021-03-12 06:10 UTC, sbs2001 commented
@pombredanne  that's already done via https://github.com/nexB/vulnerablecode/commit/d8ce30e29c0d3257a1d00d89feb0afa753ba3f69