Fix ubuntu_usn importer for invalid CVE
nexB/vulnerablecode pull request #432
Opened 2021-04-06 10:26 UTC by AmitGupta7580

Error:

![image](https://user-images.githubusercontent.com/57043342/113686762-3ffaa480-96e5-11eb-9eae-2e60d1835f23.png)

Fixed:

![image](https://user-images.githubusercontent.com/57043342/113697235-902b3400-96f0-11eb-8eaa-44a135eac94d.png)

2021-04-07 08:58 UTC, sbs2001 requested changes

2021-04-07 08:58 UTC, sbs2001 commented on vulnerabilities/importers/ubuntu_usn.py
>                      continue
skipping entirely would be bad idea as we'll be losing other data. 

Instead I suggest 

```
  if not is_cve(cve):
                    cve = ""
```

2021-04-08 11:14 UTC, AmitGupta7580 commented on vulnerabilities/importers/ubuntu_usn.py
>                      continue
Yes, It's a good idea as empty CVE will automatically takes the VULCOID-X-X-X.

2021-04-08 11:24 UTC, AmitGupta7580 commented
Around 600-700 vulnerabilities increased now.

![image](https://user-images.githubusercontent.com/57043342/114018526-f6e45500-988a-11eb-9736-5ed899c3d628.png)

![image](https://user-images.githubusercontent.com/57043342/114018264-abca4200-988a-11eb-9074-783b801127a4.png)

2021-04-12 06:08 UTC, sbs2001 approved these changes
Thanks @AmitGupta7580  I'm merging this

2021-04-12 06:12 UTC, merged