Allow default improver to improve without affected packages
nexB/vulnerablecode pull request #693
Opened 2022-04-11 18:52 UTC by TG1999

Signed-off-by: Tushar Goel <tushar.goel.dav@gmail.com>

2022-04-15 12:43 UTC, pombredanne commented on vulnerabilities/tests/test_default_improver.py
> +    assert [
create an expected var. and use the order results == expected.

2022-04-15 12:44 UTC, pombredanne requested changes
LGTM... but consider using file-driven tests for easier maintenance and updates. You my the nginx test branch merged first.

2022-04-18 11:59 UTC, pombredanne commented on vulnerabilities/tests/test_default_improver.py
> +    if regen:
We will need to switch to this kind of approach IMHO, e.g. using commoncode plus this test helper: `util_tests.check_results_against_json()` here and below.
https://github.com/nexB/vulnerablecode/blob/d1f21983d39592b7470a1db038d66c0031053b30/vulnerabilities/tests/test_nginx.py#L232

2022-04-18 12:27 UTC, pombredanne approved these changes
Thanks!

2022-04-18 13:56 UTC, merged

2022-04-18 15:25 UTC, pombredanne commented on vulnerabilities/tests/test_default_improver.py
> +    with open(response_file, "r") as f:
"r" is always the default FWIW, so not needed in general

2022-04-19 11:38 UTC, Hritik14 commented on vulnerabilities/improvers/default.py
> +            return None
Return type is an iterable