add a PyPa importer , organize the code using a shared osv.py
nexB/vulnerablecode pull request #780
Opened 2022-06-22 21:12 UTC by ziadhany

Signed-off-by: Ziad <ziadhany2016@gmail.com>

2022-06-28 10:14 UTC, TG1999 requested changes

2022-06-29 11:59 UTC, TG1999 commented
@ziadhany this looks good to me, have you verified that these importers work and have you ran the default improver over the imported data?

2022-06-29 15:34 UTC, ziadhany commented
> @ziadhany this looks good to me, have you verified that these importers work and have you ran the default improver over the imported data?

pysec and pypa importer run as expected but some package have a invalid version range .
ex: https://github.com/pypa/advisory-database/blob/main/vulns/django/PYSEC-2009-4.yaml
```
  versions:
  - 1.0.1
  - 1.0.2
  - 1.0.3
  - "1.1" <--- 
```
and some weird like this 
ex : https://github.com/pypa/advisory-database/blob/f4f630e3fabbeb545c0baabe9b0d3da264732f02/vulns/jw.util/PYSEC-2020-341.yaml 
```
  versions:
  - -class.-jw.util.version.Version-
```
should I remove the quotas or make a issue in `univers` or ignore this ?

2022-07-14 12:16 UTC, TG1999 commented
```
'PYSEC-2006-1' InvalidVersion("'2.0.0-final')
'PYSEC-2020-230' InvalidVersion("'0.1.0-dev')
```
@ziadhany try to strip the comas when univers fails to parse this.

```
  versions:
  - -class.-jw.util.version.Version-
```

Just ignore this, we can't parse this. This is invalid 
```
Traceback (most recent call last):
  File "/home/ziad/Desktop/open_source/vulnerablecode/vulnerabilities/management/commands/improve.py", line 59, in improve_data
    ImproveRunner(improver).run()
  File "/home/ziad/Desktop/open_source/vulnerablecode/vulnerabilities/improve_runner.py", line 41, in run
    process_inferences(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/ziad/Desktop/open_source/vulnerablecode/vulnerabilities/improve_runner.py", line 65, in process_inferences
    for inference in inferences:
  File "/home/ziad/Desktop/open_source/vulnerablecode/vulnerabilities/improvers/default.py", line 59, in get_inferences
    yield Inference.from_advisory_data(
  File "/home/ziad/Desktop/open_source/vulnerablecode/vulnerabilities/improver.py", line 93, in from_advisory_data
    return cls(
  File "<string>", line 10, in __init__
  File "/home/ziad/Desktop/open_source/vulnerablecode/vulnerabilities/improver.py", line 50, in __post_init__
    assert (
AssertionError
Failed to run improver vulnerabilities.improvers.default.DefaultImprover. Continuing...
CommandError: 1 failed!: vulnerabilities.improvers.default.DefaultImprover
```
other than this I was not able to reproduce this issue, can you add some logs and tell us how the data looks like there

2022-07-21 11:30 UTC, TG1999 commented
@ziadhany any updates on this?

2022-07-21 19:55 UTC, ziadhany commented
> @ziadhany any updates on this?

Pypa importer logs 
```
Importing data using vulnerabilities.importers.pypa.PyPaImporter
unsupported file .id-allocator
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2021-121' InvalidVersion("'trunk' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2021-338' InvalidVersion("'4.11-final' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2006-1' InvalidVersion("'2.0.0-final' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2008-3' InvalidVersion("'2.0.0-final' is not a valid <class 'univers.versions.PypiVersion'>")
Invalid Version - PypiVersion - 'PYSEC-2021-371' - '0.2.0-n653'
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2018-100' InvalidVersion("'0.3m1' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2022-34' InvalidVersion("'0.2.4dev' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2019-23' InvalidVersion("'0.2.4dev' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2022-167' InvalidVersion("'0.2.4dev' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2019-120' InvalidVersion("'2.2.0-dev' is not a valid <class 'univers.versions.PypiVersion'>")
Invalid Version - PypiVersion - 'PYSEC-2019-125' - '2019-09-12'
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2021-97' InvalidVersion("'1dev' is not a valid <class 'univers.versions.PypiVersion'>")
PackageURL ValueError - 'PYSEC-2022-228' - purl: 'pkg:pypi:gerapy'
PackageURL ValueError - 'PYSEC-2022-227' - purl: 'pkg:pypi:bottle'
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2020-341' InvalidVersion("'-class.-jw.util.version.Version-' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2018-115' InvalidVersion("'0.3.1-p1' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2018-114' InvalidVersion("'0.3.1-p1' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2019-6' InvalidVersion("'0.7.10p1' is not a valid <class 'univers.versions.PypiVersion'>")
PackageURL ValueError - 'PYSEC-2022-233' - purl: 'pkg:pypi:openssh-key-parser'
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2017-47' InvalidVersion("'0.7.1.fix1' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2022-12' InvalidVersion("'0.7.1.fix1' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2015-24' InvalidVersion("'0.7.1.fix1' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2017-46' InvalidVersion("'0.7.1.fix1' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2015-25' InvalidVersion("'0.7.1.fix1' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2019-126' InvalidVersion("'a3' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2017-41' InvalidVersion("'a3' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2021-428' InvalidVersion("'0.1.0.dev' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2022-166' InvalidVersion("'0.1-bulbasaur' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2018-19' InvalidVersion("'0.1-bulbasaur' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2008-8' InvalidVersion("'0.1-bulbasaur' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2019-102' InvalidVersion("'2013-01-21T20:33:09+0100' is not a valid <class 'univers.versions.PypiVersion'>")
PackageURL ValueError - 'PYSEC-2022-234' - purl: 'pkg:pypi:poetry'
PackageURL ValueError - 'PYSEC-2022-232' - purl: 'pkg:pypi:nvflare'
PackageURL ValueError - 'PYSEC-2022-231' - purl: 'pkg:pypi:nvflare'
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2017-103' InvalidVersion("'1.0beta6.1' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2022-5' InvalidVersion("'2.0.1rc2-git' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2019-106' InvalidVersion("'2.0.1rc2-git' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2021-859' InvalidVersion("'2.0.1rc2-git' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2021-356' InvalidVersion("'2.0.1rc2-git' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2020-216' InvalidVersion("'1.3.1dev' is not a valid <class 'univers.versions.PypiVersion'>")
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2012-1' InvalidVersion("'1.3.1dev' is not a valid <class 'univers.versions.PypiVersion'>")
PackageURL ValueError - 'PYSEC-2021-874' - purl: 'pkg:pypi:pytorch-lightning'
InvalidVersionRange affected_pkg_version_range Error - 'PYSEC-2020-230' InvalidVersion("'0.1.0-dev' is not a valid <class 'univers.versions.PypiVersion'>")
PackageURL ValueError - 'PYSEC-2021-872' - purl: 'pkg:pypi:distributed'
PackageURL ValueError - 'PYSEC-2022-230' - purl: 'pkg:pypi:lxml'
PackageURL ValueError - 'PYSEC-2022-229' - purl: 'pkg:pypi:gradio'
PackageURL ValueError - 'PYSEC-2021-873' - purl: 'pkg:pypi:gradio'
Successfully imported data using vulnerabilities.importers.pypa.PyPaImporter
```
Pysec importer logs :
```
/home/ziad/Desktop/open_source/vulnerablecode/venv/bin/python /home/ziad/Desktop/open_source/vulnerablecode/manage.py import vulnerabilities.importers.pysec.PyPIImporter
Importing data using vulnerabilities.importers.pysec.PyPIImporter
NotImplementedError PyPI package file_name: OSV-2021-449.json
NotImplementedError PyPI package file_name: GHSA-22gh-3r9q-xf38.json
NotImplementedError PyPI package file_name: GHSA-22jr-vc7j-g762.json
NotImplementedError PyPI package file_name: GHSA-22p3-qrh9-cx32.json
NotImplementedError PyPI package file_name: GHSA-22wc-c9wj-6q2v.json
NotImplementedError PyPI package file_name: GHSA-232r-66cg-79px.json
NotImplementedError PyPI package file_name: GHSA-23c7-6444-399m.json
NotImplementedError PyPI package file_name: GHSA-23hm-7w47-xw72.json
NotImplementedError PyPI package file_name: GHSA-246w-56m2-5899.json
NotImplementedError PyPI package file_name: GHSA-2473-9hgq-j7xw.json
NotImplementedError PyPI package file_name: GHSA-247x-2f9f-5wp7.json
NotImplementedError PyPI package file_name: GHSA-24x4-6qmh-88qg.json
NotImplementedError PyPI package file_name: GHSA-24x6-8c7m-hv3f.json
NotImplementedError PyPI package file_name: GHSA-2647-c639-qv2j.json
NotImplementedError PyPI package file_name: GHSA-267x-w5hx-8hjr.json
NotImplementedError PyPI package file_name: GHSA-26j7-6w8w-7922.json
NotImplementedError PyPI package file_name: GHSA-278g-rq84-9hmg.json
NotImplementedError PyPI package file_name: GHSA-27j5-4p9v-pp67.json
NotImplementedError PyPI package file_name: GHSA-27p5-7 [...]

2022-07-25 11:14 UTC, TG1999 commented
@ziadhany please also provide logs for default improver here.

2022-07-25 11:24 UTC, TG1999 commented
@ziadhany what is the reason behind this log and can you also point us to the function that logs this error. `NotImplementedError PyPI package file_name: OSV-2021-449.json` and

2022-07-25 11:37 UTC, ziadhany commented
@TG1999 `pysec.py line 40 : advisory_data` this for validation pysec package

2022-07-25 13:40 UTC, ziadhany commented
DefaultImprover logs :
```
Improving data using vulnerabilities.improvers.default.DefaultImprover
Inconsistent summary for <Vulnerability: VULCOID-4D>. Existing: The App.Undo.UndoSupport.get_request_var_or_attr function in Zope before 2.12.21 and 3.13.x before 2.13.11, as used in Plone before 4.2.3 and 4.3 before beta 1, allows remote authenticated users to gain access to restricted attributes via unspecified vectors., provided: The App.Undo.UndoSupport.get_request_var_or_attr function in Zope before 2.12.21 and 2.13.x before 2.13.11, as used in Plone before 4.2.3 and 4.3 before beta 1, allows remote authenticated users to gain access to restricted attributes via unspecified vectors.
Inconsistent summary for <Vulnerability: VULCOID-4D>. Existing: The App.Undo.UndoSupport.get_request_var_or_attr function in Zope before 2.12.21 and 3.13.x before 2.13.11, as used in Plone before 4.2.3 and 4.3 before beta 1, allows remote authenticated users to gain access to restricted attributes via unspecified vectors., provided: The App.Undo.UndoSupport.get_request_var_or_attr function in Zope before 2.12.21 and 2.13.x before 2.13.11, as used in Plone before 4.2.3 and 4.3 before beta 1, allows remote authenticated users to gain access to restricted attributes via unspecified vectors.
Inconsistent summary for <Vulnerability: VULCOID-VZ>. Existing: Due to use of unsafe YAML deserialization logic, an attacker with the ability to modify local YAML configuration files could provide malicious input, resulting in remote code execution or similar risks. This issue affects ParlAI prior to v1.1.0., provided: parlai is a framework for training and evaluating AI models on a variety of openly available dialogue datasets. In affected versions the package is vulnerable to YAML deserialization attack caused by unsafe loading which leads to Arbitary code execution. This security bug is patched by avoiding unsafe loader users should update to version above v1.1.0. If upgrading is not possible then users can change the Loader used to SafeLoader as a workaround. See commit 507d066ef432ea27d3e201da08009872a2f37725 for details.
Inconsistent summary for <Vulnerability: VULCOID-W3>. Existing: The module `AccessControl` defines security policies for Python code used in restricted code within Zope applications. Restricted code is any code that resides in Zope's object database, such as the contents of `Script (Python)` objects. The policies defined in `AccessControl` severely restrict access to Python modules and only exempt a few that are deemed safe, such as Python's `string` module. However, full access to the `string` module also allows access to the class `Formatter`, which can be overridden and extended within `Script (Python)` in a way that provides access to other unsafe Python libraries. Those unsafe Python libraries can be used for remote code execution. By default, you need to have the admin-level Zope "Manager" role to add or edit `Script (Python)` objects through the web. Only sites that allow untrusted users to add/edit these scripts through the web - which would be a very unusual configuration to begin with - are at risk. The problem has been fixed in AccessControl 4.3 and 5.2. Only AccessControl versions 4 and 5 are vulnerable, and only on Python 3, not Python 2.7. As a workaround, a site administrator can restrict adding/editing `Script (Python)` objects through the web using the standard Zope user/role permission mechanisms. Untrusted users should not be assigned the Zope Manager role and adding/editing these scripts through the web should be restricted to trusted users only. This is the default configuration in Zope., provided: Zope is an open-source web application server. Zope versions prior to versions 4.6.3 and 5.3 have a remote code execution security issue. In order to be affected, one must use Python 3 for one's Zope deployment, run Zope 4 below version 4.6.3 or Zope 5 below version 5.3, and have the optional `Products.PythonScripts` add-on package installed. By default, one must have the admin-level Zope "Manager" role to add or edit Script (Python) objects through the web. Only sites that allow untrusted users to add/edit these scripts through the web are at risk. Zope releases 4.6.3 and 5.3 are not vulnerable. As a workaround, a site administrator can restrict adding/editing Script (Python) objects through the web using the standard Zope user/role permission mechanisms. Untrusted users should not be assigned the Zope Manager role and adding/editing these scripts through the web should be restricted to trusted users only. This is the default configuration in Zope.
Inconsistent summary for <Vulnerability: VULCOID-W3>. Existing: The module `AccessControl` defines security policies for Python code used in restricted code within Zope applications. Restricted code is any code that resides in Zope's object database, such as the contents of `Script (Python)` objects. The policies defined in `AccessControl` severely restrict access to Python modules and only exempt a few that are deemed safe, such as Python's `string` module. However, full access to the `string` module also allows access to the class `Formatter`, which can be overridden and extended within `Script (Python)` in a way that provides access to other unsafe Python libraries. Those unsafe Python libraries can be used for remote code execution. By default, you need to have the admin-level Zope "Manager" role to add or edit `Script (Python)` objects through the web. Only sites that allow untrusted users to add/edit these scripts through the web - which would be a very unusual configuration to begin with - are at risk. The problem has been fixed in AccessControl 4.3 and 5.2. Only AccessControl versions 4 and 5 are vulnerable, and only on Python 3, not Python 2.7. As a workaround, a site administrator can restrict adding/editing `Script (Python)` objects through the web using the standard Zope user/role permission mechanisms. Untrusted users should not be assigned the Zope Manager role and adding/editing these scripts through the web should be restricted to trusted users only. This is the default configuration in Zope., provided: Zope is an open-source web application server. Zope versions prior to versions 4.6.3 and 5.3 have a remote code execution security issue. In order to be affected, one must use Python 3 for one's Zope deployment, run Zope 4 below version 4.6.3 or Zope 5 below version 5.3, and have the optional `Products.PythonScripts` add-on package installed. By default, one must have the admin-level Zope "Manager" role to add or edit Script (Python) objects through the web. Only sites that allow untrusted users to add/edit these scripts through the web are at risk. Zope releases 4.6.3 and 5.3 are not vulnerable. As a workaround, a site administrator can restrict adding/editing Script (Python) objects through the web using the standard Zope user/role permission mechanisms. Untrusted users should not be assigned the Zope Manager role and adding/editing these scripts through the web should be restricted to trusted users only. This is the default configuration in Zope.
Inconsistent summary for <Vulnerability: VULCOID-W3>. Existing: The module `AccessControl` defines security policies for Python code used in restricted code within Zope applications. Restricted code is any code that resides in Zope's object database, such as the contents of `Script (Python)` objects. The policies defined in `AccessControl` severely restrict access to Python modules and only exempt a few that are deemed safe, such as Python's `string` module. However, full access to the `string` module also allows access to the class `Formatter`, which can be overridden and extended within `Script (Python)` in a way that provides access to other unsafe Python libraries. Those unsafe Python libraries can be used for remote code execution. By default, you need to have the admin-level Zope "Manager" role to add or edit `Script (Python)` objects th [...]

2022-09-09 21:59 UTC, merged

2022-09-09 22:00 UTC, pombredanne commented
All merged... Feel free to check the few updates I made. Thanks you ++