add osv validator
nexB/vulnerablecode pull request #788
Opened 2022-07-05 09:39 UTC by keshav-space

- add test for osv

Signed-off-by: Keshav Priyadarshi <git@keshav.space>

2022-09-05 19:45 UTC, TG1999 commented
Add doctsrings for all the functions and also add doctests/ unit tests for functions which have not been tested at all

2022-09-09 22:30 UTC, pombredanne requested changes
Here are a few nit for your consideration

2022-09-09 22:30 UTC, pombredanne commented on vulntotal/datasources/osv.py
> +# Copyright (c) nexB Inc. and others. All rights reserved.
Can you use the newest style of license header for consistency?

2022-09-09 22:30 UTC, pombredanne commented on vulntotal/tests/test_osv.py
> +# Copyright (c) nexB Inc. and others. All rights reserved.
Same nit as above: we switch to simpler style of header

2022-09-09 22:30 UTC, pombredanne commented on vulntotal/datasources/osv.py
> +        for vuln in response["vulns"]:
You can use a simpler approach and remove the line above `if "vulns" in response:` with this:
```suggestion
        for vuln in response.get("vulns") or []:
```

2022-09-09 22:30 UTC, pombredanne commented on vulntotal/datasources/osv.py
> +            if "aliases" in vuln:
Prefer this:
`aliases.extend(vuln.get("aliases") or [])`

2022-09-09 22:30 UTC, pombredanne commented on vulntotal/datasources/osv.py
> +            if "id" in vuln:
Same nit as above

2022-09-09 22:30 UTC, pombredanne commented on vulntotal/datasources/osv.py
> +            if "affected" in vuln:
Prefer a .get() in most cases to an if and [item] as suggested above

2022-09-09 22:30 UTC, pombredanne commented on vulntotal/datasources/osv.py
> +                    if "events" in vuln["affected"][0]["ranges"][0]:
Always prefer extracting a variable.

2022-09-09 22:30 UTC, pombredanne commented on vulntotal/datasources/osv.py
> +def get_closest_nuget_package_name(query):
How is this specific to OSV?
May be use a nuget.py for this instead

2022-09-15 18:32 UTC, keshav-space commented
Addressed all the comments

2022-11-18 13:32 UTC, pombredanne approved these changes

2022-11-18 13:56 UTC, pombredanne approved these changes
LGTM... merging!

2022-11-18 13:56 UTC, merged