Add Snyk datasource
nexB/vulnerablecode pull request #842
Opened 2022-08-14 10:33 UTC by keshav-space

closes https://github.com/nexB/vulnerablecode/issues/834

2022-09-05 19:42 UTC, TG1999 requested changes

2022-09-05 19:42 UTC, TG1999 commented on vulntotal/datasources/snyk.py
> +    url_package_advisories = "https://security.snyk.io/package/{ecosystem}/{package}"
Add docstring

2022-09-05 19:42 UTC, TG1999 commented on vulntotal/datasources/snyk.py
> +def extract_html_json_advisories(package_advisories):
Add docstring

2022-09-05 19:42 UTC, TG1999 commented on vulntotal/datasources/snyk.py
> +def parse_html_advisory(advisory_html, snyk_id, affected) -> VendorData:
Add docstring

2022-09-05 19:42 UTC, TG1999 commented on vulntotal/datasources/snyk.py
> +                vulnerablity[anchor["href"].rsplit("/", 1)[-1]] = affected_versions
Write a function for this and write some doctests for it

2022-09-05 19:42 UTC, TG1999 commented on vulntotal/datasources/snyk.py
> +def is_purl_in_affected(version, affected):
Add docstring and doctest

2022-11-19 11:18 UTC, pombredanne commented
Merged in https://github.com/nexB/vulnerablecode/pull/1009

2022-11-19 11:18 UTC, closed without merging